
title: My Resume
#baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Chidambaram Muthappan  ## put your name
title: 'Student, Engineer &amp; Data Enthusiast'  ## your title
location: Los Angeles , CA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
linkedin: http://www.linkedin.com  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
